# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e77d862d50e41a3cc8052c901c46e79401cd8f894c000f84af04b4009cf2892f61d262aa14fbc82ca765afc3b67a175d51346170b0aed2b34047688d517de0

test:
  secret_key_base: e76e6ac7a2c3e68304d08f44f7838fe12b6fbd69e6e938bd40fa6de6541e21d6ab1c71f6ac5a5a6d7376549218385fd349a8367bef41b01ba13b45c0a0fd8ed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
